[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    Cache-Status = "\"Netlify Edge\"; hit"
    ETag = "\"replace-with-your-etag\""
    Vary = "Accept-Encoding"